update records r set visual_prompt=v.p from (values
('fastest-animal',$p$A peregrine falcon in a full-speed dive, wings tucked, streaking down past dramatic cliffs and storm clouds$p$),
('fastest-land-animal',$p$A cheetah sprinting across golden savanna grass at dusk, dust kicking up, low tracking angle$p$),
('largest-animal-ever',$p$A blue whale gliding through deep blue ocean, sunbeams cutting through the water, a tiny diver for scale$p$),
('largest-land-animal',$p$An African bush elephant walking toward the camera across a dusty plain at sunset, low angle$p$),
('longest-lived-vertebrate',$p$A Greenland shark drifting slowly through dark icy Arctic water beneath sea ice, faint blue light from above$p$),
('oldest-living-land-animal',$p$A giant tortoise slowly walking across a green island lawn under a soft morning sky, ocean behind$p$),
('tallest-living-animal',$p$A giraffe standing tall against a vast African sky at golden hour, acacia trees on the horizon$p$),
('mens-10000m',$p$A lone distance runner on an empty blue track at night, stadium lights, long shadow, seen from behind$p$),
('mens-1500m',$p$Spikes striking a red running track in the final lap, bell-lap blur, stadium lights at night$p$),
('mens-5000m',$p$A pack of distance runners rounding a curve on a red track under floodlights, seen from far above, faces not visible$p$),
('mens-800m',$p$A runner's silhouette leaning into a curve of a red track, backlit by stadium lights, motion blur$p$),
('mens-high-jump',$p$A high jumper silhouetted mid-arch over a bar against a dark sky and bright stadium lights$p$),
('mens-javelin-throw',$p$A javelin flying through a dark sky trailing light, stadium floodlights below$p$),
('mens-long-jump',$p$Sand exploding from a long jump pit at night, frozen spray lit by stadium lights$p$),
('mens-mile',$p$A stopwatch and an empty red running track at dawn, mist over the infield, lane lines leading away$p$),
('mens-pole-vault',$p$A pole vaulter silhouetted at the top of a vault, pole bent, far above the bar, night sky and floodlights$p$),
('womens-10000m',$p$A female distance runner silhouetted on a misty track at sunrise, long stride, seen from behind$p$),
('womens-1500m',$p$A female runner's spikes kicking off the red track in a final sprint, floodlit stadium blur$p$),
('womens-5000m',$p$A line of female distance runners on a curve of a track at dusk, wide aerial view, faces not visible$p$),
('womens-800m',$p$A female runner silhouetted against stadium lights leaning through the final bend, motion blur$p$),
('womens-high-jump',$p$A female high jumper silhouetted arching over the bar, bright floodlights behind, night sky$p$),
('womens-javelin-throw',$p$A female athlete silhouette releasing a javelin toward a sunset sky, javelin catching the light$p$),
('womens-long-jump',$p$A female long jumper silhouetted mid-flight above a sand pit, sand spraying, golden light$p$),
('womens-mile',$p$An empty red track at dusk with a glowing finish line and a lap counter showing the final lap$p$),
('womens-pole-vault',$p$A female pole vaulter silhouetted upside down over a high bar against a deep blue twilight sky$p$),
('mlb-al-single-season-home-runs',$p$A baseball rocketing off a bat into a night sky over a packed ballpark, light trails$p$),
('mlb-career-hits',$p$A wooden bat making contact with a baseball, splinters and dust, extreme slow motion close-up$p$),
('mlb-career-home-runs',$p$A home run ball arcing high over an outfield wall into the stands at night, fireworks in the distance$p$),
('mlb-career-rbis',$p$A runner sliding into home plate in a cloud of dust, catcher reaching, evening ballpark light, faces obscured$p$),
('mlb-career-saves',$p$A pitcher's hand gripping a baseball on the mound under bright night lights, ninth inning tension$p$),
('mlb-career-shutouts',$p$A vintage scoreboard with rows of zeros, an empty old-time ballpark at dusk, sepia tones$p$),
('mlb-career-stolen-bases',$p$A base runner's cleats digging into dirt, sliding headfirst into second base, dust cloud, low angle$p$),
('mlb-career-strikeouts-pitcher',$p$A baseball smacking into a catcher's mitt, dust bursting from the leather, extreme close-up$p$),
('mlb-career-wins-pitcher',$p$An antique baseball glove and worn ball on a wooden bench in an old-time ballpark, early 1900s feel$p$),
('mlb-consecutive-games-played',$p$A ballpark lit up night after night, timelapse of a calendar of games, glowing stadium lights$p$),
('mlb-fastest-pitch',$p$A baseball blurring toward the catcher's mitt, a radar gun readout glowing, extreme speed$p$),
('mlb-highest-career-batting-average',$p$A vintage Negro Leagues ballpark at dusk, wooden bleachers, a bat leaning on the dugout rail$p$),
('mlb-highest-single-season-batting-average',$p$Old-time ballpark at golden hour, a weathered bat and ball on home plate, film grain$p$),
('mlb-longest-home-run-statcast',$p$A baseball soaring impossibly high over a stadium upper deck into the night, tracking line drawn in light$p$),
('mlb-most-gold-gloves',$p$A golden baseball glove resting on a pitcher's mound, dramatic spotlight, empty stadium$p$),
('mlb-most-strikeouts-nine-inning-game',$p$A pitcher's arm in mid-throw silhouetted against bright stadium lights, ball leaving the hand$p$),
('mlb-most-world-series-rings-player',$p$Championship rings glittering on dark velvet, ballpark lights glowing in the background$p$),
('mlb-most-world-series-titles',$p$Confetti falling over a baseball diamond at night after a championship, stadium roaring$p$),
('mlb-single-season-hits',$p$A line drive skipping across green outfield grass, chalk line, bright sunny ballpark$p$),
('mlb-single-season-home-runs',$p$A baseball exploding off a bat at night by the water beside a ballpark, kayaks in the bay$p$),
('mlb-single-season-stolen-bases',$p$A blurred runner sprinting between bases, dirt flying from spikes, low dramatic angle$p$),
('mlb-single-season-strikeouts',$p$A fastball frozen mid-air with visible spin, stitches sharp, dark stadium behind$p$),
('nba-career-assists',$p$A basketball being passed through a crowded lane, motion blur, arena lights, faces not visible$p$),
('nba-career-games',$p$An empty basketball court with a single ball at center court, arena lights turning on one by one$p$),
('nba-career-points',$p$A basketball swishing through a net in slow motion, arena lights flaring, crowd blur$p$),
('nba-career-rebounds',$p$Hands reaching high for a basketball above the rim, silhouettes against arena lights$p$),
('nba-career-three-pointers',$p$A basketball arcing from far beyond the three-point line toward the hoop, long high arc, arena lights$p$),
('nba-longest-winning-streak',$p$A vintage 1970s basketball arena, hardwood floor, a ball on the free throw line, warm film grain$p$),
('nba-most-championships-player',$p$A row of championship rings glowing on a dark hardwood floor under a single spotlight$p$),
('nba-most-championships-team',$p$Championship banners hanging high in the rafters of a dark arena, spotlight sweeping across them$p$),
('nba-most-mvp-awards',$p$A golden trophy on a basketball court under a dramatic spotlight, arena dark around it$p$),
('nba-most-wins-season',$p$A modern arena erupting with light and confetti after a win, court seen from above$p$),
('nba-single-game-points',$p$A small 1960s arena, packed wooden bleachers, a ball dropping through an old net, black and white feel$p$),
('nba-single-season-scoring-average',$p$A vintage scoreboard flickering with large numbers in a smoky 1960s arena$p$),
('highest-bridge',$p$A towering bridge spanning a deep misty canyon, cars tiny on the deck, clouds drifting far below$p$),
('longest-bridge',$p$A viaduct stretching to the horizon across rice paddies and water, a high-speed train racing along it, aerial$p$),
('longest-suspension-bridge-span',$p$A giant suspension bridge with red towers over a blue strait at sunset, ships passing below, aerial$p$),
('largest-stadium',$p$An enormous cricket stadium packed with fans at night, floodlights blazing, aerial view$p$),
('tallest-building',$p$The Burj Khalifa piercing clouds above Dubai at dusk, city lights below, slow upward tilt$p$),
('ncaa-fbs-career-passing-yards',$p$A football spiraling through the night sky above a college stadium, marching band below$p$),
('ncaa-fbs-career-rushing-yards',$p$A running back's cleats tearing turf as he breaks into open field, college stadium lights, face hidden by helmet$p$),
('ncaa-fbs-coach-most-wins',$p$A college football sideline at dusk, headset on a bench, packed stadium behind, autumn leaves$p$),
('ncaa-fbs-longest-field-goal',$p$A football tumbling end over end through tall goalposts against a twilight sky$p$),
('ncaa-fbs-longest-winning-streak',$p$A 1950s college football stadium in black and white feel, leather helmets on a bench$p$),
('ncaa-fbs-season-passing-touchdowns',$p$A football dropping into a receiver's hands in the end zone, college stadium at night, helmet obscures face$p$),
('ncaa-fbs-season-rushing-yards',$p$A 1980s college football field under lights, a runner breaking a tackle, grainy broadcast look, face hidden$p$),
('ncaa-football-largest-attendance',$p$A massive motor speedway turned into a football stadium, packed stands, fireworks overhead, aerial at night$p$),
('ncaa-mens-basketball-career-points',$p$A 1970s college gym, floppy socks, a ball arcing toward the hoop, warm vintage film look$p$),
('ncaa-mens-basketball-coach-wins',$p$An empty college basketball court with a coach's clipboard on a folding chair, arena lights$p$),
('ncaa-mens-basketball-longest-streak',$p$A 1970s college basketball arena in warm film tones, a ball resting at center court$p$),
('ncaa-mens-basketball-most-titles',$p$A championship trophy on hardwood under confetti, nets cut down, college arena$p$),
('ncaa-mens-basketball-single-game-points',$p$A small 1950s college gym with wooden bleachers, a ball dropping through a net, black and white$p$),
('ncaa-most-cfp-titles',$p$A college football championship trophy under confetti on a field at night, fireworks$p$),
('ncaa-most-college-world-series-titles',$p$A college baseball field at dusk, a trophy on home plate, stadium lights warming up$p$),
('ncaa-most-heisman-winners',$p$A bronze football player trophy on a pedestal under a spotlight, dark room$p$),
('ncaa-most-team-titles-school',$p$A trophy room with rows of gleaming championship trophies, light sweeping along the shelves$p$),
('ncaa-womens-basketball-career-points',$p$A basketball swishing through the net from deep range, packed college arena, slow motion$p$),
('ncaa-womens-basketball-coach-wins',$p$A women's college basketball court at night, a whistle and clipboard on the bench, arena lights$p$),
('ncaa-womens-basketball-longest-streak',$p$A row of glowing W letters forming on an arena video board, women's college basketball court below$p$),
('ncaa-womens-basketball-most-titles',$p$Confetti falling on a women's college basketball court, nets cut down, trophy glowing$p$),
('nfl-career-interceptions',$p$A football tipped into the air above outstretched gloves, stadium lights, slow motion$p$),
('nfl-career-passing-touchdowns',$p$A football spiraling in slow motion through stadium lights toward the end zone$p$),
('nfl-career-passing-yards',$p$A football field seen from the quarterback's view, a perfect spiral flying downfield, night game$p$),
('nfl-career-points',$p$A football kicked through goalposts, stadium lights flaring, slow motion$p$),
('nfl-career-receiving-yards',$p$A receiver's gloved hands snagging a football at full extension, sideline, night game, helmet hides face$p$),
('nfl-career-receptions',$p$Close-up of gloved hands securing a football against the chest, rain and stadium lights$p$),
('nfl-career-rushing-yards',$p$Cleats churning through turf, a ball tucked under an arm, a wall of blockers, low angle$p$),
('nfl-career-sacks',$p$A defensive lineman exploding off the line at the snap, turf flying, silhouettes under lights$p$),
('nfl-career-touchdowns',$p$A football slammed down in the end zone, turf spray, stadium lights, low angle$p$),
('nfl-largest-super-bowl-margin',$p$A championship football stadium at night with fireworks and a lopsided glowing scoreboard$p$),
('nfl-longest-field-goal',$p$A football flying end over end a long way through goalposts in a desert stadium at night$p$),
('nfl-longest-winning-streak',$p$A football stadium with an electric crowd, a scoreboard showing win after win, night game$p$),
('nfl-most-coaching-wins',$p$A 1970s football sideline, a coach's headset and playbook on a bench, warm film grain$p$),
('nfl-most-points-one-team-game',$p$A vintage 1960s football stadium scoreboard with a huge number, crowd in winter coats$p$),
('nfl-most-super-bowl-titles-team',$p$A row of silver football trophies gleaming under a spotlight in a dark room$p$),
('nfl-most-super-bowl-wins-player',$p$Seven championship rings glittering on a black surface, stadium lights bokeh behind$p$),
('nfl-perfect-season',$p$A 1970s football field in sunshine, an undefeated scoreboard, warm vintage film look$p$),
('nfl-single-season-passing-touchdowns',$p$A football spiraling toward the end zone under snowy stadium lights$p$),
('nfl-single-season-passing-yards',$p$A football arcing downfield in a domed stadium, laser-straight spiral, crowd blur$p$),
('nfl-single-season-receiving-yards',$p$A receiver leaping high over defenders for a football, silhouettes against stadium lights$p$),
('nfl-single-season-rushing-yards',$p$A 1980s football field, a runner sprinting down the sideline, grainy broadcast look, face hidden$p$),
('nfl-single-season-sacks',$p$A defender bursting through the line, turf flying, quarterback silhouette going down, night game$p$),
('best-selling-console',$p$A generic black video game console glowing in a dark room, controller beside it, blue light$p$),
('best-selling-video-game',$p$A blocky voxel landscape of hills, trees and a sunrise, low-poly cubes forming terrain$p$),
('largest-esports-prize-pool',$p$A giant esports arena with screens and stage lights, crowd silhouettes, confetti cannons firing$p$),
('lowest-round-mens-major',$p$A golf ball rolling into the cup on a perfect green at golden hour, low angle$p$),
('most-golf-majors-men',$p$A golf ball on a tee at dawn, mist over a classic links course, flag in the distance$p$),
('most-lpga-majors',$p$A golf course at sunrise, a putter and ball on a dew-covered green, vintage tone$p$),
('most-pga-tour-wins',$p$A golf ball flying against a bright blue sky, fairway and gallery far below$p$),
('nhl-career-assists',$p$A hockey puck sliding across fresh ice between two sticks, rink lights reflecting$p$),
('nhl-career-goals',$p$A hockey puck rippling the back of a net, ice spray, arena lights flaring$p$),
('nhl-career-points',$p$A puck skimming across clean ice toward the goal, ice shavings flying, low angle$p$),
('nhl-career-shutouts',$p$A goalie's glove snatching a puck out of the air, ice spray, arena lights, mask hides face$p$),
('nhl-fastest-hat-trick',$p$Three hockey pucks skidding into a net one after another, ice spray, 1950s arena$p$),
('nhl-goalie-career-wins',$p$A goalie mask resting on the crossbar of a hockey net, empty rink, spotlight$p$),
('nhl-longest-winning-streak',$p$An arena erupting after a goal, red goal light flashing, ice glittering$p$),
('nhl-most-goals-single-game',$p$An outdoor-feeling 1910s hockey rink, wooden boards, a puck on rough ice, sepia tones$p$),
('nhl-most-stanley-cups-player',$p$A silver championship cup with names engraved, glowing on ice under a spotlight$p$),
('nhl-most-stanley-cups-team',$p$Championship banners hanging above a hockey rink, spotlight sweeping across the ice$p$),
('nhl-single-season-goals',$p$A 1980s hockey rink, a wrist shot flying toward the net, grainy broadcast look$p$),
('fastest-app-100-million',$p$A smartphone screen glowing in the dark as a user counter spins upward, light particles bursting$p$),
('fastest-supercomputer',$p$Endless rows of supercomputer racks with blinking blue lights, slow dolly down the aisle$p$),
('fastest-youtube-1-million',$p$A play button icon made of light exploding into a burst of particles, a counter racing upward$p$),
('largest-data-leak',$p$Streams of glowing data spilling out of a cracked digital vault, dark blue cyberspace$p$),
('most-expensive-domain',$p$A blinking cursor in an empty, glowing web browser address bar floating in a dark room, gold light$p$),
('most-followed-instagram-account',$p$A smartphone camera icon floating over a sea of glowing profile circles, pastel gradient light$p$),
('most-followed-instagram-person',$p$A stadium crowd of phone screens glowing in the dark, follow notifications rising like sparks$p$),
('most-followed-tiktok',$p$Vertical video screens stacked into a glowing tower, notification hearts floating up, dark room$p$),
('most-followed-x',$p$A flock of glowing notification icons swirling into the night sky above a city$p$),
('most-liked-instagram-post',$p$Golden confetti and a world championship trophy silhouette, hearts floating upward like lanterns$p$),
('most-liked-youtube-video',$p$A private jet over Paris at sunset, the city lights below, playful bold colors$p$),
('most-subscribed-youtube',$p$A wall of glowing video thumbnails forming a mosaic, a red subscribe button glowing in the center$p$),
('mens-marathon',$p$Thousands of marathon runners crossing a city bridge at sunrise, aerial view, faces not visible$p$),
('womens-marathon',$p$A lead runner's silhouette on a long empty city street at dawn, skyline behind$p$),
('dow-largest-point-gain',$p$A stock ticker board glowing green with numbers surging upward, trading floor blur$p$),
('dow-largest-point-loss',$p$A stock ticker board glowing red with numbers plunging, trading floor in chaos, blurred figures$p$),
('first-5-trillion-company',$p$Glowing green computer chips forming a skyline, light pulsing through circuit traces$p$),
('first-trillionaire',$p$A rocket launching at dawn beside a tower of gold coins, dramatic sky$p$),
('highest-paid-actor',$p$A red carpet and film camera under a spotlight, stacks of gold coins glowing beside it$p$),
('highest-paid-athlete',$p$A soccer ball made of gold spinning on a pitch under stadium lights$p$),
('highest-paid-musician',$p$A concert stage lit in red, a lone microphone stand, sea of lighters in the dark$p$),
('largest-acquisition',$p$Two glowing planets of light merging in space, energy swirling between them$p$),
('largest-ipo',$p$A rocket launching at dawn with a stock ticker glowing green across the sky$p$),
('largest-lottery-jackpot',$p$Lottery balls tumbling in a clear drum under bright light, golden glow$p$),
('most-expensive-car-auction',$p$A silver 1950s racing coupe gleaming under auction-house spotlights, dark room$p$),
('most-expensive-diamond',$p$A huge pink diamond rotating slowly on black velvet, light refracting into sparkles$p$),
('most-expensive-home-us',$p$A penthouse terrace above Central Park at night, Manhattan skyline glittering$p$),
('most-expensive-nft',$p$A mosaic of thousands of tiny digital artworks forming a grid, glowing pixels shifting$p$),
('most-expensive-painting-auction',$p$A Renaissance-style painting on a dark gallery wall, a single spotlight, auction paddle raised in shadow$p$),
('most-expensive-painting-private',$p$A bold abstract expressionist canvas of colorful brushstrokes on a gallery wall, spotlight$p$),
('most-expensive-sports-franchise',$p$A basketball arena in Los Angeles at night, purple and gold light, palm trees outside$p$),
('most-expensive-sports-memorabilia',$p$A vintage baseball jersey framed under museum glass, spotlight, dark room$p$),
('most-expensive-trading-card',$p$A rare trading card in a clear graded slab, holographic shine, spotlight on black velvet$p$),
('most-expensive-whisky',$p$An antique whisky bottle with amber liquid catching candlelight, dark wood background$p$),
('most-expensive-wine',$p$A dusty 1945 wine bottle in a candlelit cellar, red wine pouring into crystal$p$),
('most-valuable-company',$p$A futuristic glowing data center skyline, green light pulsing through server towers$p$),
('richest-person',$p$A rocket lifting off at night with flames, an electric car's headlights in the foreground$p$),
('richest-woman',$p$A sunlit modern art museum gallery in the Ozark hills, glass walls, quiet water outside$p$),
('f1-fastest-lap',$p$A Formula 1 car blasting down a tree-lined straight, motion blur, sparks from the floor$p$),
('f1-fastest-race',$p$A Formula 1 car screaming past a historic grandstand, heat haze, extreme speed blur$p$),
('f1-most-constructors-titles',$p$A red Formula 1 car in a pit lane under dramatic light, crew silhouettes, sparks$p$),
('f1-most-pole-positions',$p$A Formula 1 car at the front of an empty starting grid, red lights above glowing$p$),
('f1-most-wins',$p$A Formula 1 car crossing the finish line under a waving checkered flag, confetti$p$),
('f1-most-wins-season',$p$A Formula 1 car racing through a night street circuit, city lights reflecting on the bodywork$p$),
('f1-most-world-championships',$p$A Formula 1 trophy on a podium under champagne spray, fireworks behind$p$),
('f1-youngest-champion',$p$A Formula 1 car racing at twilight past a glowing hotel on a desert circuit$p$),
('indy-fastest-indy-500',$p$An IndyCar at full speed on a huge oval, grandstands blurred, heat shimmer$p$),
('indy-fastest-qualifying-run',$p$A lone IndyCar on an empty oval track at extreme speed, 1990s broadcast look$p$),
('indy-most-championships',$p$A vintage open-wheel race car on a sunny oval, 1960s film tones$p$),
('indy-most-indy-500-poles',$p$An IndyCar alone on the front row of a massive oval track at dawn$p$),
('indy-most-indy-500-wins',$p$A bottle of milk raised in victory lane, confetti, oval grandstands behind, face not visible$p$),
('lemans-greatest-distance',$p$A prototype race car at night on a long straight, headlights cutting through darkness, 24-hour race$p$),
('lemans-most-wins-driver',$p$An endurance race car rounding a curve at dawn, headlights still on, mist over the track$p$),
('lemans-most-wins-manufacturer',$p$A white endurance race car racing at night, glowing brake discs, long exposure light trails$p$),
('nascar-fastest-qualifying-lap',$p$A stock car on a steep high-banked oval at extreme speed, 1980s broadcast look$p$),
('nascar-most-consecutive-titles',$p$A stock car crossing under a checkered flag at night, sparks and confetti$p$),
('nascar-most-consecutive-wins',$p$A 1960s stock car on a sunny oval, vintage film look, dust and crowds$p$),
('nascar-most-cup-championships',$p$A row of championship trophies on a stage under spotlights, stock cars behind$p$),
('nascar-most-cup-wins',$p$A vintage blue stock car taking a victory lap, 1970s film grain, crowd cheering$p$),
('nascar-most-daytona-500-wins',$p$Stock cars racing three wide on a massive banked oval at dusk, aerial view$p$),
('nascar-most-wins-season',$p$A 1960s stock car leading a pack on a dirt-dusted oval, sun glare, vintage tone$p$),
('biggest-opening-weekend',$p$A packed movie theater lit by a bright screen, audience silhouettes cheering$p$),
('highest-grossing-animated-film',$p$A glowing mythical lotus and swirling flames in a dark sky, painterly animation style$p$),
('highest-grossing-film',$p$A cosmic battle sky with streaking lights over a dark city, epic scale, no characters$p$),
('most-oscar-acting-nominations',$p$A golden statuette on a stage under a spotlight, theater curtains, glitter falling$p$),
('most-oscars-film',$p$Rows of golden statuettes on a table glittering under a spotlight, theater curtains$p$),
('most-oscars-person',$p$An old animation studio desk with hand-drawn cels and a golden statuette, warm lamp light$p$),
('best-selling-album-us',$p$A vinyl record spinning on a turntable, warm light, a desert highway at sunset behind a window$p$),
('best-selling-album-worldwide',$p$A vinyl record spinning under red and purple light, a 1980s dance floor glowing behind$p$),
('best-selling-single',$p$A vintage radio glowing beside a snowy window on a winter night, candles, warm light$p$),
('highest-grossing-concert-tour',$p$A massive stadium concert stage with light beams and confetti, sea of fans, aerial$p$),
('largest-concert-attendance-female-artist',$p$A huge beach concert at night, crowd stretching for miles along the shore, aerial$p$),
('largest-free-concert-attendance',$p$A massive crowd on a beach at night facing a glowing stage, fireworks over the ocean$p$),
('most-album-of-the-year-grammys',$p$A golden gramophone trophy spinning under a spotlight on a dark stage$p$),
('most-billboard-200-number-one-albums',$p$A row of vinyl records on a shelf, a turntable spinning, 1960s warm film look$p$),
('most-cma-entertainer-of-the-year',$p$A country music stage with spotlights and a cowboy hat on a stool, crowd in shadow$p$),
('most-grammy-nominations',$p$A row of golden gramophone trophies glowing in the dark, light sweeping across$p$),
('most-grammy-wins',$p$Golden gramophone trophies multiplying in a mirror room, glittering light$p$),
('most-hot-100-number-ones-artist',$p$Vintage 45 rpm singles stacked and spinning, 1960s jukebox glowing$p$),
('most-ifpi-global-artist-of-the-year',$p$A globe made of light spinning above a concert stage, glittering beams$p$),
('most-riaa-certified-units-artist',$p$Platinum records lining a dark wall, light sweeping across the discs$p$),
('most-spotify-monthly-listeners',$p$A pair of headphones glowing in the dark, sound waves pulsing out in rings$p$),
('most-streamed-artist-spotify-2025',$p$A neon-lit Caribbean street at night, speakers pulsing, palm trees, vibrant colors$p$),
('most-streamed-song-spotify',$p$A neon-lit night drive through a city, red light streaks, retro synthwave mood$p$),
('most-viewed-youtube-video',$p$Colorful cartoon-style ocean waves and bubbles, playful bright colors, no characters$p$),
('most-weeks-number-one-billboard-200',$p$A 1960s movie soundtrack record spinning, New York fire escapes at sunset behind$p$),
('most-weeks-number-one-hot-100-song',$p$A Texas highway at golden hour, a pickup truck kicking up dust, radio glowing inside$p$),
('oldest-artist-hot-100-number-one',$p$A vintage jukebox glowing beside a decorated Christmas tree, snow outside the window$p$),
('deadliest-earthquake',$p$Ancient loess cliffs cracking and crumbling in a valley at dusk, dust rising, no people$p$),
('deepest-lake',$p$Crystal-clear blue ice on a vast frozen lake, cracks running toward mountains, winter sun$p$),
('deepest-point-in-ocean',$p$A submersible's lights descending into absolute darkness, marine snow drifting past$p$),
('highest-mountain',$p$Mount Everest at sunrise above a sea of clouds, wind blowing snow off the summit$p$),
('highest-waterfall',$p$A waterfall plunging off a huge flat-topped mountain into mist, jungle below, aerial$p$),
('largest-country',$p$A vast snowy taiga forest stretching to the horizon, a long train crossing it, aerial$p$),
('largest-earthquake',$p$Ocean waves surging against a rocky Chilean coast under a stormy sky, ground cracking$p$),
('largest-hot-desert',$p$Endless orange sand dunes in the Sahara at sunset, wind blowing sand off the crests, aerial$p$),
('largest-island',$p$Massive ice sheet and glaciers of Greenland calving into the sea, aerial at golden hour$p$),
('largest-lake',$p$A huge calm inland sea at sunrise, shoreline stretching to the horizon, aerial$p$),
('largest-ocean',$p$Endless Pacific Ocean swells under a dramatic sky, aerial, no land in sight$p$),
('largest-volcanic-eruption',$p$A volcano erupting with a towering ash column and lightning in the plume, night sky$p$),
('longest-river',$p$A river winding through desert like a green ribbon, aerial at golden hour$p$),
('tallest-tsunami',$p$A giant wave crashing up a forested mountainside in a narrow Alaskan bay, aerial$p$),
('most-gold-medals-single-games',$p$A swimming pool lane at night, water rippling, gold medals glinting on the starting block$p$),
('most-olympic-gold-medals',$p$A pile of gold medals on a pool deck, water droplets, stadium lights$p$),
('most-olympic-medals',$p$A swimmer's silhouette diving into a glowing blue pool, splash frozen, arena lights$p$),
('most-summer-olympic-golds-country',$p$Gold medals on ribbons swaying in the wind, an Olympic-style stadium at night behind$p$),
('most-winter-olympic-medals',$p$A cross-country skier silhouetted on a snowy ridge at sunrise, snow spraying$p$),
('oldest-living-person',$p$A calm English garden at dawn, a wooden bench and a cup of tea, soft warm light$p$),
('oldest-man-ever',$p$A peaceful Japanese seaside village at sunrise, fishing boats and calm water$p$),
('oldest-person-ever',$p$A sunny Provençal street in Arles, cafes and old stone, warm afternoon light$p$),
('shortest-person-ever',$p$A tiny pair of shoes beside a measuring tape in a Himalayan village, soft light$p$),
('tallest-living-person',$p$A doorway in an old stone house with a height chart reaching above the frame, warm light$p$),
('tallest-person-ever',$p$A 1930s Midwestern street, a giant pair of shoes on a shop step, sepia film look$p$),
('highest-transfer-fee',$p$A soccer ball rolling across a Paris stadium pitch at night, Eiffel Tower lights in the distance$p$),
('most-ballon-dor',$p$A golden soccer ball trophy rotating under a spotlight, glitter falling$p$),
('most-career-goals-men',$p$A soccer ball bulging the back of a net under stadium lights, rain, slow motion$p$),
('most-international-goals-men',$p$A soccer ball curling into the top corner of a goal, flags waving in the stands$p$),
('most-world-cup-goals',$p$A soccer ball rocketing into the net in a packed World Cup stadium at night, confetti$p$),
('most-world-cup-titles',$p$Yellow and green confetti raining over a soccer pitch, stadium lights, celebrating crowd blur$p$),
('farthest-humans-from-earth',$p$The far side of the Moon passing below a spacecraft window, Earth small and distant$p$),
('fastest-humans',$p$A space capsule blazing through the atmosphere, plasma trail glowing orange$p$),
('longest-single-spaceflight',$p$A space station orbiting above Earth's curve, sunrise flaring over the horizon$p$),
('most-time-in-space',$p$The International Space Station passing over Earth at night, city lights below$p$),
('fastest-crewed-aircraft',$p$A black rocket plane streaking across the upper atmosphere, Earth's curve below$p$),
('fastest-jet-aircraft',$p$A sleek black jet streaking across the sky at extreme altitude, sun glinting$p$),
('fastest-maglev-train',$p$A white maglev train speeding through a tunnel exit, extreme motion blur, Japan countryside$p$),
('fastest-wheeled-train',$p$A high-speed train blasting through French countryside, fields blurring past$p$),
('land-speed-record',$p$A jet-powered car blasting across a flat desert playa, dust plume trailing for miles$p$),
('water-speed-record',$p$A jet boat skimming across a still lake at extreme speed, spray rooster tail$p$),
('mens-1000m-speed-skating',$p$A speed skater's blades slicing the ice in a low crouch, ice spray, oval lights, face hidden$p$),
('mens-1500m-speed-skating',$p$Speed skating blades cutting a curve on gleaming ice, motion blur, close-up$p$),
('mens-5000m-speed-skating',$p$A long-track speed skating oval from above, a lone skater tracing the curve$p$),
('mens-500m-speed-skating',$p$A speed skater exploding off the start line, ice shavings flying, dramatic lights, face hidden$p$),
('womens-1000m-speed-skating',$p$A female speed skater in a deep crouch on gleaming ice, motion blur, face hidden$p$),
('womens-1500m-speed-skating',$p$Close-up of skate blades cutting a perfect line through ice, sparkle of shavings$p$),
('womens-5000m-speed-skating',$p$An empty speed skating oval glowing under arena lights, a lone skater in the distance$p$),
('womens-500m-speed-skating',$p$A female speed skater's start, ice spray exploding, arena lights, face hidden$p$),
('mens-100m',$p$A sprinter exploding out of the blocks on a red track under stadium lights, sparks of motion, face not visible$p$),
('mens-200m',$p$A sprinter silhouette powering around a curve under bright stadium lights, motion blur$p$),
('mens-400m',$p$A lone sprinter's shadow stretching down a red track at sunset, stadium empty$p$),
('womens-100m',$p$A female sprinter blasting from the blocks, red track, flash of stadium lights, face not visible$p$),
('womens-200m',$p$A female sprinter silhouette racing around the curve at night, motion blur$p$),
('womens-400m',$p$A red track at sunset with lane numbers glowing, starting blocks in lane four$p$),
('deepest-borehole',$p$A rusted, welded-shut borehole cap in a frozen Arctic wasteland, snow blowing$p$),
('longest-rail-tunnel',$p$A train racing through a long lit tunnel deep under the Alps, light streaks$p$),
('longest-road-tunnel',$p$A road tunnel with glowing blue caverns of light deep inside a mountain, car headlights$p$),
('tallest-dam',$p$A towering concrete arch dam in a deep green gorge releasing white water, aerial$p$),
('tallest-statue',$p$A colossal bronze statue rising above a river at sunrise, mist drifting, aerial$p$),
('tallest-tower',$p$Tokyo Skytree glowing against a twilight sky, the city lighting up below$p$),
('mens-100m-backstroke',$p$A swimmer gliding on his back through a glowing pool, underwater view, bubbles$p$),
('mens-100m-breaststroke',$p$An underwater view of a breaststroke kick, bubbles trailing, blue light$p$),
('mens-100m-butterfly',$p$A butterfly swimmer surging out of the water, arms wide, spray frozen, face hidden$p$),
('mens-100m-freestyle',$p$An underwater view of a freestyle swimmer streaking down a lane, bubbles and light rays$p$),
('mens-200m-freestyle',$p$A swimmer's flip turn underwater, bubbles exploding off the wall, blue light$p$),
('mens-200m-individual-medley',$p$A swimmer diving into a glowing pool, perfect entry, water crown splash$p$),
('mens-400m-freestyle',$p$Aerial view of a long blue pool lane, a lone swimmer pulling ahead, lane ropes$p$),
('mens-50m-freestyle',$p$A swimmer launching off the starting block mid-air, water below, arena lights$p$),
('womens-100m-backstroke',$p$Underwater view of a backstroke start, bubbles rising, blue light rays$p$),
('womens-100m-breaststroke',$p$A breaststroke swimmer rising for air, water spraying, close-up, face hidden by goggles and splash$p$),
('womens-100m-butterfly',$p$A butterfly swimmer lifting out of the water, wings of spray, arena lights$p$),
('womens-100m-freestyle',$p$Underwater view of a freestyle swimmer, light ripples on the pool floor$p$),
('womens-200m-freestyle',$p$A female swimmer gliding underwater after a turn, streamlined, bubbles trailing$p$),
('womens-200m-individual-medley',$p$A swimmer dives into a glowing lane, light refracting through the splash$p$),
('womens-400m-freestyle',$p$Aerial view of a pool at night, a single swimmer leaving a wake of light$p$),
('womens-50m-freestyle',$p$A swimmer's hand slapping the touch pad at the wall, explosion of water$p$),
('most-grand-slams-men',$p$A tennis ball skidding off a hard court line, chalk dust, night stadium lights$p$),
('most-grand-slams-women',$p$A grass tennis court at a vintage tournament, wooden racket on the net, 1960s tone$p$),
('most-weeks-at-no-1-tennis',$p$A tennis ball in slow motion hitting the strings of a racket, fibers flexing$p$),
('most-wimbledon-titles',$p$A pristine grass tennis court at golden hour, white lines, ball rolling to the net$p$),
('deadliest-tornado',$p$A dark tornado over flat green farmland under a stormy sky, distant and ominous, no people$p$),
('deadliest-tropical-cyclone',$p$A massive cyclone spiraling over the ocean, seen from space, eye clearly visible$p$),
('heaviest-hailstone',$p$Giant hailstones bouncing and shattering on a wet field, storm clouds above, slow motion$p$),
('highest-air-pressure',$p$A frozen Siberian landscape under a crystal clear deep blue sky, still air, sparkling frost$p$),
('highest-recorded-temperature',$p$Heat haze shimmering over Death Valley salt flats, a thermometer glowing red$p$),
('highest-tornado-wind-speed',$p$A huge tornado tearing across Oklahoma plains at golden hour, dust and debris swirling$p$),
('highest-wave-buoy',$p$A giant ocean wave rearing up in a North Atlantic storm, a lone buoy riding the crest$p$),
('highest-wind-gust',$p$A tropical cyclone's winds bending palm trees sideways on a remote island, rain lashing$p$),
('largest-hailstone-us',$p$A huge hailstone held up against a dark South Dakota storm sky, close-up, ice layers visible$p$),
('longest-dry-period',$p$Cracked dry earth of the Atacama Desert, a lone cactus, cloudless sky$p$),
('longest-lasting-tropical-cyclone',$p$A cyclone swirling across the Indian Ocean in a satellite view, timelapse$p$),
('longest-lightning-flash-distance',$p$A single bolt of lightning stretching across the entire night sky over the Great Plains$p$),
('longest-lightning-flash-duration',$p$Branching lightning crawling slowly across the sky over South American grasslands at night$p$),
('longest-tornado-path',$p$A 1920s farm landscape under an enormous storm cloud, sepia tones, tornado in the distance$p$),
('lowest-air-pressure',$p$A massive typhoon from space with an enormous swirling eye, glowing in sunlight$p$),
('lowest-recorded-temperature',$p$A research station in Antarctica at night, frost and ice crystals, aurora overhead$p$),
('most-rainfall-12-months',$p$Torrential monsoon rain over lush green Indian hills and waterfalls, mist$p$),
('most-rainfall-24-hours',$p$Sheets of rain lashing a volcanic tropical island, waterfalls bursting from cliffs$p$),
('most-rainfall-one-hour',$p$A Midwestern town street flooded by sudden rain, water rushing, gray sky$p$),
('most-snowfall-one-season-us',$p$A ski lodge buried in towering snow drifts, snow falling heavily, Cascade mountains$p$),
('widest-tornado',$p$An enormous wide tornado filling the horizon over Oklahoma farmland, lightning flashing$p$),
('mlb-longest-hitting-streak',$p$A 1940s ballpark in summer haze, a line drive bouncing into the outfield, vintage film grain$p$)
) v(s,p) where r.slug=v.s;